#!/bin/bash

if [[ $1 == "-h" ]]
then
echo "Add a dpdk port to OVS"
echo ""
echo "-b | --bridge:    bridge to add port to"
echo "-p | --port:      port name (dpdk0, dpdk1, ...)"
echo "-r | --rx-queues: number of RX queues"
echo "-a | --rx-aff:    RX queues affinity (e.g. \"0:0,1:2\")"
echo "-s | --rx-size:   RX queues size (e.g. 1000)"
echo "-t | --tx-queues: number of TX queues"
echo "-f | --tx-aff:    TX queues affinity (e.g. \"0:0,1:2\")"
echo "-z | --tx-size:   TX queues size"
exit 0
fi

set -x
source vars.sh

while [[ $# -gt 1 ]]
do
key="$1"
case $key in
-b|--bridge)
    BRIDGE="$2"
    shift 
    ;;

-p|--port)
    PORT="$2"
    shift 
    ;;

-r|--rx-queues)
    RX_QUEUES="$2"
    shift 
    ;;

-a|--rx-aff)
    RX_QUEUES_AFF="$2"
    shift 
    ;;

-s|--rx-size)
    RX_QUEUES_SIZE="$2"
    shift 
    ;;

-t|--tx-queues)
    TX_QUEUES="$2"
    shift 
    ;;

-z|--tx-size)
    TX_QUEUES_SIZE="$2"
    shift 
    ;;

-f|--tx-aff)
    TX_QUEUES_AFF="$2"
    shift 
    ;;

*)
    ;;
esac
shift 
done


sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
	add-port $BRIDGE $PORT -- set Interface $PORT type=dpdk 
sleep $SLEEP_SECS 

if [[ -v RX_QUEUES ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT options:n_rxq=$RX_QUEUES
fi

if [[ -v RX_QUEUES_SIZE ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT options:n_rxq_desc=$RX_QUEUES_SIZE
fi

if [[ -v RX_QUEUES_AFF ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT other_config:pmd-rxq-affinity=\"${RX_QUEUES_AFF}\"
fi

if [[ -v TX_QUEUES ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT options:n_txq=$TX_QUEUES
fi

if [[ -v TX_QUEUES_SIZE ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT options:n_txq_desc=$TX_QUEUES_SIZE
fi

if [[ -v TX_QUEUES_AFF ]]
then
	sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK \
   		set Interface $PORT other_config:pmd-txq-affinity=\"${TX_QUEUES_AFF}\"
fi
