#!/bin/bash
if [[ $1 == "-h" ]]
then
echo "Add bridge to OVS"
echo ""
echo "-b | --bridge: bridge name"
exit 0
fi

set -x
source vars.sh

while [[ $# -gt 1 ]]
do
key="$1"
case $key in
-b|--bridge)
    BRIDGE="$2"
    shift 
    ;;

*)
    ;;
esac
shift 
done

sudo $OVS_DIR/utilities/ovs-vsctl --db=unix:$OVSDB_SOCK --no-wait \
	add-br $BRIDGE -- set bridge $BRIDGE datapath_type=netdev

sleep $SLEEP_SECS
