#! /usr/bin/env python3

from vswitch.ovdk import OvsDpdk
import logging
import argparse


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="----[%(asctime)s ]: %(message)s")
    parser = argparse.ArgumentParser(description='Add bridge to OVS-DPDK')
    parser.add_argument('--bridge', dest='bridge', action='store', help='Bridge name')
    args = parser.parse_args()

    ovdk = OvsDpdk()
    ovdk.br_add(args.bridge)