#! /usr/bin/env python3

from vswitch.ovdk import OvsDpdk
import logging
import argparse

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="----[%(asctime)s ]: %(message)s")
    parser = argparse.ArgumentParser(description='Add a DPDK port to an OVS-DPDK bridge')
    parser.add_argument('--bridge', dest='bridge', action='store', help='Bridge name')
    parser.add_argument('--port', dest='port', action='store', help='Port name (e.g. dpdk0)')
    parser.add_argument('--rx-queues', dest='rx_queues', action='store', help='Number of RX queues')
    parser.add_argument('--rx-aff', dest='rx_aff', action='store', help='RX queues affinity (e.g. "0:0,1:2")')
    parser.add_argument('--rx-size', dest='rx_size', action='store', help='RX queues size (e.g. 1000)')
    parser.add_argument('--tx-queues', dest='tx_queues', action='store', help='Number of TX queues')
    parser.add_argument('--tx-aff', dest='tx_aff', action='store', help='TX queues affinity (e.g. "0:0,1:2")')
    parser.add_argument('--tx-size', dest='tx_size', action='store', help='TX queues size (e.g. 1000)')
    args = parser.parse_args()

    ovdk = OvsDpdk()
    ovdk.dpdk_port_add(args.bridge, args.port, args.rx_queues, args.rx_aff, args.rx_size, args.tx_queues, args.tx_aff,
                       args.tx_size)
