#! /usr/bin/env python3

from vswitch.ovdk import OvsDpdk
import logging
import argparse

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="----[%(asctime)s ]: %(message)s")
    parser = argparse.ArgumentParser(description='Add a vhost-user port to an OVS-DPDK bridge')
    parser.add_argument('--bridge', dest='bridge', action='store', help='Bridge name')
    parser.add_argument('--port', dest='port', action='store', help='Port name (e.g. vhost-user1)')
    args = parser.parse_args()

    ovdk = OvsDpdk()
    ovdk.vhost_port_add(args.bridge, args.port)
