#! /usr/bin/env python3

from vswitch.vs import OvsDpdk
import logging
import argparse

if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG, format="----[%(asctime)s ]: %(message)s")
    parser = argparse.ArgumentParser(description='Delete a port from an OVS-DPDK bridge')
    parser.add_argument('--bridge', dest='bridge', action='store', help='Bridge name')
    parser.add_argument('--port', dest='port', action='store', help='Port name (e.g. dpdk0)')
    args = parser.parse_args()

    ovdk = OvsDpdk()
    ovdk.port_del(args.bridge, args.port)
