#!/bin/bash

source vars.sh

mkdir -p $BASE_DIR/tarballs
wget -nc http://dpdk.org/browse/dpdk/snapshot/dpdk-16.07.zip -P $BASE_DIR/tarballs
unzip -n $BASE_DIR/tarballs/dpdk-16.07.zip -d $BASE_DIR
pushd $DPDK_DIR
make install T=$DPDK_TARGET DESTDIR=install
popd
