#!/bin/bash

if [[ $1 == "-h" ]]
then
echo "Delete a port from an OVS bridge"
echo ""
echo "-b | --bridge:    bridge to delete port from"
echo "-p | --port:      port name"
exit 0
fi

set -x
source vars.sh

while [[ $# -gt 1 ]]
do
key="$1"
case $key in
-b|--bridge)
    BRIDGE="$2"
    shift 
    ;;

-p|--port)
    PORT="$2"
    shift 
    ;;

*)
    ;;
esac
shift 
done

sudo $OVS_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVSDB_SOCK del-port $BRIDGE $PORT
sleep $SLEEP_SECS 
