#!/bin/bash
# $1: bridge to add interface to
# $2: interface name (e.g. dpdk0)

source vars.sh


# Create an interface mapped to the first dpdk bound interface 
$OVS_DPDK_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVS_DB_SOCK add-port fastbr0 dpdk0 -- set Interface dpdk0 type=dpdk 
sleep 1 
 
# Configure 2 rx queues for the first dpdk interface (optional step) 
$OVS_DPDK_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVS_DB_SOCK --no-wait set Interface dpdk0 options:n_rxq=2 
sleep 1 
 
# Configure the rx queues ? core affinities for the dpdk interface (optional) 
$OVS_DPDK_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVS_DB_SOCK --no-wait  set interface dpdk0 options:n_rxq=2 other_config:pmd-rxq-affinity="0:0,1:2" 
sleep 1 
 
# Configure 2 tx queues for the dpdk interface (optional step) 
$OVS_DPDK_DIR/utilities/ovs-vsctl --no-wait --db=unix:$OVS_DB_SOCK --no-wait set Interface dpdk0 options:n_txq=2 
sleep 1
