#!/bin/bash

if [[ $1 == "-h" ]]
then
echo "Add a port to port flow"
echo ""
echo "-b | --bridge:    bridge to add flow to"
echo "-i | --in-port:   input port (e.g. LOCAL | 1 | 2 | ...)"
echo "-o | --out-ports:  comma separated output port(s) (e.g. LOCAL,1,2,...)"
exit 0
fi

set -x
source vars.sh

while [[ $# -gt 1 ]]
do
key="$1"
case $key in
-b|--bridge)
    BRIDGE="$2"
    shift 
    ;;

-i|--in_port)
    IN_PORT="$2"
    shift 
    ;;

-o|--out-ports)
    OUT_PORTS="$2"
    shift 
    ;;

*)
    ;;
esac
shift 
done

declare -A pmap



sudo $OVS_DIR/utilities/ovs-ofctl add-flow $BRIDGE in_port=$IN_PORT,action=output:$OUT_PORTS
sleep $SLEEP_SECS 

