#!/bin/bash

source vars.sh

# start ovsdb server
$OVS_DIR/ovsdb/ovsdb-server --remote=punix:$OVS_DB_SOCK \
			    --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
			    --pidfile \
			    --detach $OVS_DB_CONF
