#!/bin/bash

source vars.sh
# start ovsdb server
$OVS_DIR/ovsdb/ovsdb-server --remote=punix:$OVSDB_SOCK \
			    --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
			    --pidfile \
			    --detach \
			    $OVSDB_CONF
