#!/bin/bash
set -x
source vars.sh

wget -nc http://wiki.qemu-project.org/download/qemu-${QEMU_VERSION}.tar.bz2 -P $BASE_DIR/tarballs
tar -jxvf $BASE_DIR/tarballs/qemu-${QEMU_VERSION}.tar.bz2 --directory $BASE_DIR
pushd $QEMU_DIR
./configure --target-list=x86_64-softmmu --enable-debug --enable-kvm --enable-numa
make
popd
